[project]
authors = ["chend <chend@janelia.hhmi.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "n5-zarr"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyterlab = "*"
pixi-kernel = "*"
python = "3.10.*"
numpy = ">=2.0.1,<3"
zarr = ">=2.18.2,<3"
numcodecs = ">=0.12.1,<0.13"
pathlib = ">=1.0.1,<2"
ipykernel = ">=6.29.5,<7"
fsspec = ">=2024.9.0,<2025"
google-crc32c = ">=1.1.2,<2"

[pypi-dependencies]
tensorstore = ">=0.1.64, <0.2"

[target.win-64.dependencies]
crc32c = ">=2.7.1,<3"

[target.osx-64.dependencies]
crc32c = ">=2.7.1,<3"

[target.linux-64.dependencies]
crc32c = ">=2.7.1,<3"
